'use client';

import { FormEvent, useEffect, useState } from 'react';

type Lang = 'ar' | 'en';
const services = [
  {
    n:'01', glyph:'◒', ar:'قياس التحول الرقمي', en:'Digital Transformation Measurement',
    descAr:'نساعد الجهات على فهم مستوى نضجها الرقمي والاستعداد لدورات القياس، من مراجعة الممارسات والأدلة إلى معالجة الفجوات ومتابعة التحسين. نربط متطلبات القياس بمبادرات واضحة ومسؤوليات محددة تدعم تقدماً مستداماً.',
    descEn:'We help organizations understand their digital maturity and prepare for assessment cycles, from reviewing practices and evidence to closing gaps and tracking improvements. We translate assessment requirements into clear initiatives and accountable ownership.',
    pointsAr:['تقييم الممارسات الحالية وتحليل الفجوات مقابل متطلبات القياس ذات الصلة بالجهة.','إعداد خطة تحسين مرتبة حسب الأولوية، مع تحديد المسؤوليات والجداول الزمنية ومؤشرات المتابعة.','تنظيم الأدلة والوثائق ومراجعة اكتمالها واتساقها مع الممارسات المطبقة.','تنفيذ مراجعات جاهزية وورش عمل لتأهيل الفرق على متطلبات القياس وآليات التوثيق.','متابعة إغلاق الملاحظات وإعداد تقارير دورية توضح التقدم وفرص رفع النضج.'],
    pointsEn:['Assess current practices and identify gaps against the assessment requirements relevant to the organization.','Develop a prioritized improvement plan with owners, timelines, and progress indicators.','Organize supporting evidence and review its completeness and consistency with implemented practices.','Conduct readiness reviews and workshops on assessment requirements and evidence documentation.','Track corrective actions and report progress and opportunities to improve digital maturity.'],
  },
  {
    n:'02', glyph:'▦', ar:'البنية المؤسسية', en:'Enterprise Architecture',
    descAr:'نربط أهداف الجهة بقدرات الأعمال والبيانات والتطبيقات والتقنية لبناء رؤية متكاملة للوضع الحالي والمستهدف. نساعد فرقكم على توجيه الاستثمارات، وتقليل ازدواجية الحلول، وتحديد مسار انتقال عملي نحو البنية المستهدفة.',
    descEn:'We connect organizational goals with business capabilities, data, applications, and technology to create a coherent view of current and target architectures. We help teams guide investment decisions, reduce duplication, and plan a practical transition.',
    pointsAr:['تأسيس وتفعيل مكتب البنية المؤسسية، وتحديد نموذج التشغيل والأدوار ومنهجية العمل.','توثيق قدرات الأعمال والخدمات والعمليات وعلاقاتها بالبيانات والتطبيقات والبنية التقنية.','تصميم البنية المستهدفة والمبادئ والمعايير المرجعية لتوجيه تطوير الحلول.','إعداد تحليل الفجوات وخارطة الانتقال وربطها بمحفظة المبادرات والاستثمارات.','تفعيل حوكمة المعماريات ومراجعة الحلول وتحديث مستودع البنية ونقل المعرفة للفرق.'],
    pointsEn:['Establish an Enterprise Architecture Office with an operating model, roles, and working methodology.','Map business capabilities, services, and processes to data, applications, and technology infrastructure.','Define target architectures, principles, and reference standards to guide solution design.','Develop gap analyses and transition roadmaps linked to initiative and investment portfolios.','Enable architecture governance, solution reviews, repository maintenance, and team knowledge transfer.'],
  },
  {
    n:'03', glyph:'◎', ar:'الحوكمة والمخاطر والامتثال', en:'Governance, Risk & Compliance',
    descAr:'نطوّر منظومة مترابطة للحوكمة وإدارة المخاطر والامتثال توضح آليات اتخاذ القرار والمساءلة. نساعد الجهة على تحديد مخاطرها، وتصميم الضوابط المناسبة، ومتابعة الالتزام بالسياسات والمتطلبات ذات الصلة بأعمالها.',
    descEn:'We develop connected governance, risk, and compliance practices that clarify decision-making and accountability. We help organizations identify risks, design appropriate controls, and monitor adherence to policies and requirements relevant to their operations.',
    pointsAr:['تصميم أطر الحوكمة واللجان ومصفوفات الصلاحيات والمسؤوليات وآليات التصعيد.','إعداد وتحديث السياسات والإجراءات وربطها بملاكها ودورات المراجعة والاعتماد.','تحديد المخاطر وتقييم احتمالاتها وآثارها وإعداد سجلاتها وخطط المعالجة.','ربط متطلبات الامتثال بالضوابط والأدلة وتقييم الفجوات ومتابعة الإجراءات التصحيحية.','إعداد مؤشرات المخاطر والامتثال وتقارير تساعد اللجان والإدارة على اتخاذ القرار.'],
    pointsEn:['Design governance frameworks, committee structures, authority matrices, and escalation paths.','Develop and update policies and procedures with clear ownership, review cycles, and approvals.','Identify risks, assess likelihood and impact, and maintain risk registers and treatment plans.','Map compliance requirements to controls and evidence, assess gaps, and track corrective actions.','Define risk and compliance indicators and reporting that supports management and committee decisions.'],
  },
  {
    n:'04', glyph:'⌁', ar:'المؤشرات الوطنية', en:'National Indicators',
    descAr:'نمكّن الجهات من إدارة أدائها على المؤشرات الوطنية ذات الصلة باختصاصها عبر تحويل المتطلبات إلى بيانات موثوقة وخطط عمل قابلة للمتابعة. نوضح مسؤوليات القياس ونحلل أسباب الفجوات لدعم الجاهزية وتحسين الأداء.',
    descEn:'We help organizations manage performance against national indicators relevant to their mandate by translating requirements into reliable data and trackable action plans. We clarify measurement ownership and analyze performance gaps to support readiness and improvement.',
    pointsAr:['حصر المؤشرات والمتطلبات ذات الصلة وتحديد تعريفاتها ونطاق تطبيقها داخل الجهة.','تحديد ملاك المؤشرات ومصادر البيانات ودورية التحديث وآليات التحقق من الجودة.','بناء خط أساس للأداء وتحليل الفجوات والأسباب المؤثرة في النتائج.','إعداد خطط تحسين تربط الإجراءات بالمستهدفات والمسؤوليات والمواعيد.','تطوير لوحات متابعة وتقارير جاهزية ومراجعة الأدلة الداعمة لنتائج المؤشرات.'],
    pointsEn:['Identify relevant indicators and requirements, their definitions, and their organizational scope.','Assign indicator owners, data sources, update frequencies, and quality verification procedures.','Establish performance baselines and analyze gaps and the factors driving results.','Create improvement plans linking actions to targets, accountable owners, and deadlines.','Develop monitoring dashboards and readiness reports, and review evidence supporting indicator results.'],
  },
  {
    n:'05', glyph:'✦', ar:'الابتكار الرقمي', en:'Digital Innovation',
    descAr:'نساعد الجهات على بناء ممارسة ابتكار مستمرة تبدأ بتحديد التحديات وتنتهي باختبار الحلول وقياس جدواها. نجمع بين احتياجات المستفيدين وأولويات الأعمال لاستكشاف أفكار رقمية قابلة للتجربة والتطوير والتوسع.',
    descEn:'We help organizations build an ongoing innovation practice, from defining challenges to testing solutions and evaluating feasibility. We combine beneficiary needs with business priorities to identify digital ideas that can be piloted, refined, and scaled.',
    pointsAr:['إعداد استراتيجية الابتكار ونموذج الحوكمة وآليات استقبال الأفكار وفرزها وتقييمها.','تنفيذ ورش اكتشاف التحديات والتفكير التصميمي بمشاركة أصحاب المصلحة والمستفيدين.','تطوير تصورات الحلول والنماذج الأولية وخطط التجربة للتحقق من الفرضيات.','تقييم الأثر المتوقع والجدوى ومتطلبات التنفيذ وترتيب مبادرات الابتكار حسب الأولوية.','بناء محفظة ابتكار ومؤشرات لنتائج التجارب وآليات لتوثيق التعلم واتخاذ قرارات التوسع.'],
    pointsEn:['Define an innovation strategy, governance model, and processes for collecting and evaluating ideas.','Facilitate challenge discovery and design-thinking workshops with stakeholders and beneficiaries.','Develop solution concepts, prototypes, and pilot plans to test key assumptions.','Assess potential impact, feasibility, and implementation needs to prioritize innovation initiatives.','Build an innovation portfolio with experiment measures, documented learning, and scale-up decision criteria.'],
  },
  {
    n:'06', glyph:'◉', ar:'البيانات والذكاء الاصطناعي', en:'Data & Artificial Intelligence',
    descAr:'نساعد الجهات على تنظيم بياناتها وتحسين جودتها واستثمارها في التحليل ودعم القرار. نبني أسس الحوكمة وإدارة البيانات، ونقيّم جاهزية حالات استخدام الذكاء الاصطناعي وفق قيمة الأعمال وتوافر البيانات ومتطلبات الاستخدام المسؤول.',
    descEn:'We help organizations organize and improve their data for analytics and decision-making. We establish data governance and management foundations, then assess AI use cases based on business value, data readiness, and responsible-use requirements.',
    pointsAr:['إعداد استراتيجية البيانات ونموذج تشغيل مكتب إدارة البيانات وتحديد الأدوار والمسؤوليات.','تطوير سياسات الحوكمة وتصنيف البيانات وضوابط الوصول والمشاركة وحماية الخصوصية.','حصر أصول البيانات وبناء قاموس الأعمال والكتالوج وتعريف معايير جودة البيانات وخطط تحسينها.','تحديد الاحتياجات التحليلية وتصميم مؤشرات ولوحات معلومات تدعم القرارات التشغيلية والاستراتيجية.','تقييم حالات استخدام الذكاء الاصطناعي ووضع خارطة طريق للتجارب مع معايير التقييم والإشراف البشري.'],
    pointsEn:['Define a data strategy and Data Management Office operating model with clear roles and accountability.','Develop governance policies, data classifications, and controls for access, sharing, and privacy.','Inventory data assets, build business glossaries and catalogs, and define data quality improvement plans.','Identify analytics needs and design indicators and dashboards for operational and strategic decisions.','Assess AI use cases and plan pilots with evaluation criteria and human oversight.'],
  },
  {
    n:'07', glyph:'◌', ar:'تجربة المستفيد', en:'Beneficiary Experience',
    descAr:'نضع احتياجات المستفيد في صميم تصميم الخدمات، وندرس رحلته عبر القنوات الرقمية وغير الرقمية لاكتشاف نقاط التعثر. نترجم نتائج البحث إلى تحسينات في الإجراءات والمحتوى والواجهات، مع قياس سهولة الاستخدام ورضا المستفيد.',
    descEn:'We put beneficiary needs at the center of service design and examine journeys across digital and offline channels to uncover friction. We translate research into improvements to processes, content, and interfaces, supported by usability and satisfaction measurement.',
    pointsAr:['تنفيذ مقابلات واستبيانات وأبحاث لفهم احتياجات المستفيدين وتوقعاتهم وسلوكهم.','رسم رحلات المستفيد الحالية والمستهدفة وتحديد نقاط الألم وفرص تحسين الخدمة.','إعداد مخططات الخدمة لربط التجربة الأمامية بالإجراءات والفرق والأنظمة الداعمة.','تطوير تصورات ونماذج أولية للواجهات والمحتوى واختبار سهولة الاستخدام وإمكانية الوصول.','تعريف مؤشرات الرضا والجهد وإتمام الخدمة وبناء آلية مستمرة لاستقبال الملاحظات والتحسين.'],
    pointsEn:['Conduct interviews, surveys, and research to understand beneficiary needs, expectations, and behavior.','Map current and target journeys to identify pain points and service improvement opportunities.','Create service blueprints connecting the front-end experience to supporting teams, processes, and systems.','Develop interface and content concepts and prototypes, and evaluate usability and accessibility.','Define satisfaction, effort, and completion measures with an ongoing feedback and improvement process.'],
  },
  {
    n:'08', glyph:'□', ar:'إدارة الجودة الشاملة', en:'Total Quality Management',
    descAr:'نساعد الجهات على بناء عمليات واضحة ومتسقة ترفع جودة المخرجات وتحد من الهدر وإعادة العمل. نطوّر منظومة الجودة من توثيق الإجراءات وتحديد مؤشرات الأداء إلى تحليل أسباب المشكلات وتفعيل التحسين المستمر.',
    descEn:'We help organizations build clear, consistent processes that improve output quality and reduce waste and rework. We develop quality practices spanning documented procedures, performance measurement, root-cause analysis, and continuous improvement.',
    pointsAr:['تقييم منظومة الجودة وحصر العمليات وتحديد ملاكها ومدخلاتها ومخرجاتها ونقاط الرقابة.','نمذجة وإعادة تصميم العمليات لتبسيط الإجراءات وتحسين تدفق العمل وتوضيح المسؤوليات.','إعداد أدلة الجودة والسياسات والإجراءات والنماذج وآليات ضبط الوثائق وتحديثها.','تصميم مؤشرات لقياس جودة المخرجات ومدة الإنجاز والكفاءة ومتابعة فرص التحسين.','دعم المراجعات الداخلية وتحليل الأسباب الجذرية ومتابعة الإجراءات التصحيحية ونقل المعرفة.'],
    pointsEn:['Assess quality practices and map processes, owners, inputs, outputs, and control points.','Model and redesign processes to simplify procedures, improve workflow, and clarify responsibilities.','Develop quality manuals, policies, procedures, templates, and document control practices.','Design indicators for output quality, turnaround time, and efficiency to track improvement opportunities.','Support internal reviews, root-cause analysis, corrective-action follow-up, and knowledge transfer.'],
  },
];
const projects = [
  { no:'01', clientAr:'جامعة القصيم', clientEn:'Qassim University', typeAr:'التحول الرقمي', typeEn:'Digital Transformation', titleAr:'خارطة طريق التحول الرقمي المؤسسي', titleEn:'Institutional Digital Transformation Roadmap', descAr:'تشخيص النضج الرقمي وتحديد المبادرات ذات الأولوية وبناء خارطة تنفيذ مترابطة تدعم مستهدفات الجامعة.', descEn:'Assessing digital maturity, prioritizing initiatives, and building an integrated execution roadmap aligned with the university’s goals.', tagsAr:['قياس النضج','خارطة الطريق','حوكمة المبادرات'], tagsEn:['Maturity','Roadmap','Governance'], tone:'violet' },
  { no:'02', clientAr:'جامعة القصيم', clientEn:'Qassim University', typeAr:'البنية المؤسسية', typeEn:'Enterprise Architecture', titleAr:'تأسيس وتفعيل البنية المؤسسية', titleEn:'Enterprise Architecture Establishment', descAr:'تصميم نموذج التشغيل وبناء المعماريات الحالية والمستهدفة وربطها بمحفظة المبادرات والتقنيات.', descEn:'Designing the operating model, developing baseline and target architectures, and linking them to the initiative and technology portfolio.', tagsAr:['نموذج التشغيل','المعماريات','المحفظة التقنية'], tagsEn:['Operating Model','Architectures','Technology Portfolio'], tone:'navy' },
  { no:'03', clientAr:'الهيئة السعودية للملكية الفكرية', clientEn:'Saudi Authority for Intellectual Property', typeAr:'التحول الرقمي', typeEn:'Digital Transformation', titleAr:'برنامج تمكين التحول الرقمي', titleEn:'Digital Transformation Enablement Program', descAr:'مواءمة مستهدفات التحول مع الأولويات المؤسسية، وتطوير نموذج متابعة يقيس التقدم والأثر بوضوح.', descEn:'Aligning transformation goals with institutional priorities and developing a monitoring model that clearly measures progress and impact.', tagsAr:['الاستراتيجية','القياس','إدارة التغيير'], tagsEn:['Strategy','Measurement','Change'], tone:'blue' },
  { no:'04', clientAr:'الهيئة السعودية للملكية الفكرية', clientEn:'Saudi Authority for Intellectual Property', typeAr:'البنية المؤسسية', typeEn:'Enterprise Architecture', titleAr:'مواءمة الأعمال والتقنية', titleEn:'Business–Technology Alignment', descAr:'تطوير مرجعيات البنية المؤسسية وآليات الحوكمة لدعم القرارات الاستثمارية وتحسين التكامل بين الأعمال والتقنية.', descEn:'Developing enterprise architecture references and governance mechanisms to guide investment decisions and improve business–technology integration.', tagsAr:['هندسة الأعمال','حوكمة التقنية','المرجعيات'], tagsEn:['Business Architecture','IT Governance','Reference Models'], tone:'sand' },
];
const copy = {
  ar: { nav:['من نحن','الخدمات','المنهجية','المشاريع','تواصل معنا'], eyebrow:'شريكك في التحول المؤسسي', title:'نحوّل الطموح الرقمي إلى أثرٍ مؤسسي.', intro:'نعمل من داخل المنظومة لربط الاستراتيجية بالتنفيذ، وبناء قدرات رقمية مستدامة وقابلة للقياس.', primary:'استكشف خدماتنا', secondary:'ابدأ رحلتك الرقمية', marker:'خبرات وطنية · أثر قابل للقياس', heroStat:'مجالات خبرة متكاملة', aboutLabel:'من نحن', aboutTitle:'نبني التحول من داخل المنظومة.', aboutText:'ركيزة التحول شركة استشارية سعودية متخصصة في تمكين الجهات من تحويل المبادرات الرقمية المتفرقة إلى أثر مؤسسي مستدام. يجمع فريقنا بين الرؤية الاستراتيجية والخبرة التنفيذية لنصنع حلولاً تتبنّاها فرق العمل وتستمر بعد انتهاء المشروع.', values:[['فريق وطني','استشاريون ومحللو أعمال بخبرة في القطاع الحكومي'],['منهجية عملية','مخرجات قابلة للتطبيق والقياس منذ اليوم الأول'],['شراكة حقيقية','نقل معرفة وبناء قدرات داخلية مستدامة']], servicesLabel:'خدماتنا', servicesTitle:'خبرة متكاملة. أثر واحد.', servicesIntro:'ثمانية مجالات مترابطة تأخذ منظمتك من التشخيص والتخطيط إلى التنفيذ والتحسين المستمر.', details:'تفاصيل الخدمة', outputs:'ما الذي نقدّمه', methodLabel:'طريقتنا', methodTitle:'منهجية واضحة من أربع خطوات', steps:[['01','نفهم','نفهم السياق والطموح والتحديات من أصحاب المصلحة.'],['02','نُشخّص','نقيس الوضع الراهن ونحدّد الفجوات والأولويات.'],['03','نصمّم','نبني الحل وخارطة الطريق ومؤشرات النجاح.'],['04','نُمكّن','ننفّذ مع فرقكم وننقل المعرفة ونقيس الأثر.']], projectsLabel:'مشاريع حديثة', projectsTitle:'شراكات تصنع أثراً مستداماً', projectsIntro:'نماذج من أعمالنا في التحول الرقمي والبنية المؤسسية مع جهات وطنية رائدة.', contactLabel:'لنبدأ الحوار', contactTitle:'جاهزون لتحويل التحدّي القادم إلى فرصة.', contactText:'شاركنا احتياجك، وسيتواصل معك فريقنا لمناقشة المسار الأنسب.', fields:['الاسم الكامل','البريد الإلكتروني','الجهة / المنظمة','كيف يمكننا مساعدتك؟'], send:'إرسال الطلب عبر واتساب', direct:'أو تواصل معنا مباشرة', rights:'© 2026 شركة ركيزة التحول — المملكة العربية السعودية' },
  en: { nav:['About','Services','Approach','Projects','Contact'], eyebrow:'Your institutional transformation partner', title:'Turning digital ambition into institutional impact.', intro:'We work from within your ecosystem to connect strategy with execution and build sustainable, measurable digital capabilities.', primary:'Explore our services', secondary:'Start your digital journey', marker:'National expertise · Measurable impact', heroStat:'Integrated areas of expertise', aboutLabel:'About us', aboutTitle:'We build transformation from within.', aboutText:'Transformation Pillar Company is a Saudi consultancy that helps organizations turn fragmented digital initiatives into lasting institutional impact. Our team combines strategic vision with hands-on delivery to create solutions that teams adopt and sustain beyond the engagement.', values:[['National team','Consultants and business analysts with government-sector expertise'],['Practical approach','Actionable, measurable outputs from day one'],['True partnership','Knowledge transfer and sustainable internal capability building']], servicesLabel:'Our services', servicesTitle:'Integrated expertise. One impact.', servicesIntro:'Eight connected domains that take your organization from assessment and planning to execution and continuous improvement.', details:'Service details', outputs:'What we deliver', methodLabel:'Our approach', methodTitle:'A clear four-step methodology', steps:[['01','Understand','We uncover the context, ambition, and stakeholder challenges.'],['02','Assess','We measure the current state and identify gaps and priorities.'],['03','Design','We shape the solution, roadmap, and success measures.'],['04','Enable','We execute with your teams, transfer knowledge, and measure impact.']], projectsLabel:'Recent projects', projectsTitle:'Partnerships that create lasting impact', projectsIntro:'Selected digital transformation and enterprise architecture engagements with leading national entities.', contactLabel:'Start a conversation', contactTitle:'Ready to turn your next challenge into an opportunity.', contactText:'Tell us what you need and our team will reach out to discuss the best path forward.', fields:['Full name','Email address','Organization','How can we help?'], send:'Send request via WhatsApp', direct:'Or reach us directly', rights:'© 2026 Transformation Pillar Company — Saudi Arabia' },
};

export default function Home() {
  const [lang, setLang] = useState<Lang>('ar');
  const ar = lang === 'ar'; const t = copy[lang];
  const anchors = ['#about','#services','#approach','#projects','#contact'];
  useEffect(() => {
    document.documentElement.lang = lang;
    document.documentElement.dir = ar ? 'rtl' : 'ltr';
  }, [lang, ar]);
  function submitContact(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const data = new FormData(event.currentTarget);
    const message = ar ? `مرحباً، أنا ${data.get('name')} من ${data.get('organization')}. ${data.get('message')} — ${data.get('email')}` : `Hello, I’m ${data.get('name')} from ${data.get('organization')}. ${data.get('message')} — ${data.get('email')}`;
    window.open(`https://wa.me/966505527636?text=${encodeURIComponent(message)}`, '_blank', 'noopener,noreferrer');
  }
  return (
    <main lang={lang} dir={ar ? 'rtl' : 'ltr'} className="site-shell">
      <header className="topbar"><a href="#top" className="brand" aria-label="TPCO home"><img className="brand-logo" src="/brand/tpco-logo-white.svg" alt={ar?'شركة ركيزة التحول':'Transformation Pillar Company'} /></a><nav aria-label={ar?'التنقل الرئيسي':'Primary navigation'}>{t.nav.map((item,index)=><a key={item} href={anchors[index]}>{item}</a>)}</nav><button className="lang-switch" onClick={()=>setLang(ar?'en':'ar')} aria-label={ar?'Switch to English':'التبديل إلى العربية'}>{ar?'EN':'عربي'}</button></header>
      <section className="hero" id="top"><div className="hero-copy"><h1>{t.title}</h1><p className="hero-intro">{t.intro}</p><div className="hero-actions"><a className="button primary" href="#services">{t.primary}<span>↗</span></a><a className="button ghost" href="https://wa.me/966505527636" target="_blank" rel="noreferrer">{t.secondary}</a></div><p className="marker">{t.marker}</p></div></section>
      <section className="about section-pad" id="about"><img className="section-clip about-clip" src="/brand/clip-angle.png" alt="" aria-hidden="true" /><div className="about-head"><div><h2>{t.aboutTitle}</h2></div><p className="lead-copy">{t.aboutText}</p></div><div className="value-grid">{t.values.map(value=><article key={value[0]}><h3>{value[0]}</h3><p>{value[1]}</p></article>)}</div></section>
      <section className="services section-pad" id="services"><div className="section-heading light"><div><h2>{t.servicesTitle}</h2></div><p>{t.servicesIntro}</p></div><div className="services-grid-full">{services.map(service=><details className="service-detail" key={service.n}><summary><div className="service-top"><b className="glyph">{service.glyph}</b></div><h3>{ar?service.ar:service.en}</h3><p>{ar?service.descAr:service.descEn}</p><span className="detail-link">{t.details}<b>＋</b></span></summary><div className="detail-body"><b>{t.outputs}</b><ul>{(ar?service.pointsAr:service.pointsEn).map(point=><li key={point}>{point}</li>)}</ul></div></details>)}</div></section>
      <section className="approach section-pad" id="approach"><img className="section-clip approach-clip" src="/brand/clip-links.png" alt="" aria-hidden="true" /><h2>{t.methodTitle}</h2><div className="steps">{t.steps.map(step=><article key={step[0]}><div className="step-dot" /><h3>{step[1]}</h3><p>{step[2]}</p></article>)}</div></section>
      <section className="projects section-pad" id="projects"><div className="section-heading project-heading"><div><h2>{t.projectsTitle}</h2></div><p>{t.projectsIntro}</p></div><div className="project-grid">{projects.map(project=><article className={`project-card ${project.tone}`} key={project.no}><div className="project-visual"><div className="project-rings"><i/><i/><i/></div><span className="project-type">{ar?project.typeAr:project.typeEn}</span></div><div className="project-copy"><small>{ar?project.clientAr:project.clientEn}</small><h3>{ar?project.titleAr:project.titleEn}</h3><p>{ar?project.descAr:project.descEn}</p><div className="tags">{(ar?project.tagsAr:project.tagsEn).map(tag=><span key={tag}>{tag}</span>)}</div></div></article>)}</div></section>
      <section className="contact section-pad" id="contact"><div className="contact-copy"><h2>{t.contactTitle}</h2><p>{t.contactText}</p><div className="contact-direct"><small>{t.direct}</small><a href="https://wa.me/966505527636" target="_blank" rel="noreferrer">+966 50 552 7636 ↗</a></div></div><div className="contact-person"><img className="contact-clip" src="/brand/clip-panel.png" alt="" aria-hidden="true" /><img className="contact-photo" src="/hero-natural.png" alt={ar?'مستشار سعودي في التحول الرقمي':'Saudi digital transformation consultant'} /></div><form onSubmit={submitContact}><label>{t.fields[0]}<input required name="name" autoComplete="name" /></label><label>{t.fields[1]}<input required type="email" name="email" autoComplete="email" /></label><label>{t.fields[2]}<input required name="organization" autoComplete="organization" /></label><label className="full">{t.fields[3]}<textarea required name="message" rows={3} /></label><button className="button primary full" type="submit">{t.send}<span>↗</span></button></form></section>
      <footer><a href="#top" className="brand" aria-label="TPCO home"><img className="brand-logo footer-logo" src="/brand/tpco-logo-white.svg" alt={ar?'شركة ركيزة التحول':'Transformation Pillar Company'} /></a><p>{t.rights}</p><a href="#top" className="back-top">↑</a></footer>
    </main>
  );
}
