'use client';

import { FormEvent, useState } from 'react';

type Lang = 'ar' | 'en';
const services = [
  { n:'01', glyph:'◒', ar:'قياس التحول الرقمي', en:'Digital Transformation Measurement', descAr:'نُمكّن الجهات الحكومية من رفع مستوى الالتزام بمعايير التحول الرقمي الحكومي وتحويل نتائج القياس إلى برنامج تحسين عملي.', descEn:'We help government entities improve alignment with digital transformation standards and turn assessment results into an actionable improvement program.', pointsAr:['تقييم الوضع الراهن والفجوات','خارطة طريق رفع النضج','إدارة الأدلة ومؤشرات الامتثال'], pointsEn:['Current-state and gap assessment','Digital maturity improvement roadmap','Evidence and compliance KPI management'] },
  { n:'02', glyph:'▦', ar:'البنية المؤسسية', en:'Enterprise Architecture', descAr:'نُوائم الاستراتيجية مع الأعمال والبيانات والتطبيقات والتقنية، ونبني منهجيات مؤسسية واضحة قابلة للتنفيذ والقياس.', descEn:'We align strategy with business, data, applications, and technology while establishing practical, measurable architecture capabilities.', pointsAr:['تأسيس مكتب البنية المؤسسية','نماذج الوضع الحالي والمستهدف','حوكمة المبادرات والمحافظ التقنية'], pointsEn:['Enterprise Architecture Office setup','Baseline and target-state models','Initiative and technology portfolio governance'] },
  { n:'03', glyph:'◎', ar:'الحوكمة والمخاطر والامتثال', en:'Governance, Risk & Compliance', descAr:'نرسّخ أطر حوكمة فعّالة، ونبني سجلات المخاطر والضوابط التي تعزّز الامتثال للمتطلبات الوطنية.', descEn:'We establish effective governance frameworks, risk registers, and controls that strengthen alignment with national requirements.', pointsAr:['نماذج الحوكمة والصلاحيات','إدارة المخاطر والضوابط','لوحات متابعة الامتثال'], pointsEn:['Governance and authority models','Risk and control management','Compliance monitoring dashboards'] },
  { n:'04', glyph:'⌁', ar:'المؤشرات الوطنية', en:'National Indicators', descAr:'نساعد الجهات الحكومية على رفع مستوى التزامها بالمؤشرات والمتطلبات الوطنية عبر منهجية قياس ومتابعة متكاملة.', descEn:'We help government entities improve performance against national indicators through an integrated measurement and follow-up approach.', pointsAr:['حصر المتطلبات وملاكها','تحليل الفجوات والأولويات','تقارير الجاهزية والأداء'], pointsEn:['Requirement and ownership mapping','Gap and priority analysis','Readiness and performance reporting'] },
  { n:'05', glyph:'✦', ar:'الابتكار الرقمي', en:'Digital Innovation', descAr:'نطوّر منظومة الابتكار داخل الجهات لتحويل الأفكار إلى مبادرات رقمية قابلة للتطبيق والقياس والتوسّع.', descEn:'We develop innovation ecosystems that turn ideas into digital initiatives ready to test, measure, and scale.', pointsAr:['استراتيجية وحوكمة الابتكار','مختبرات التفكير والتصميم','إدارة المحفظة ونماذج التجربة'], pointsEn:['Innovation strategy and governance','Design and ideation labs','Portfolio and experimentation models'] },
  { n:'06', glyph:'◉', ar:'البيانات والذكاء الاصطناعي', en:'Data & Artificial Intelligence', descAr:'نؤسس مكاتب إدارة وحوكمة البيانات وفق الضوابط والمعايير الوطنية، ونهيئ البيانات لحالات استخدام ذكاء اصطناعي موثوقة.', descEn:'We establish data management and governance offices aligned with national standards and prepare trusted data for AI use cases.', pointsAr:['استراتيجية البيانات ونموذج التشغيل','الحوكمة والجودة والكتالوج','تحديد أولويات حالات استخدام الذكاء الاصطناعي'], pointsEn:['Data strategy and operating model','Governance, quality, and cataloging','AI use-case prioritization'] },
  { n:'07', glyph:'◌', ar:'تجربة المستفيد', en:'Beneficiary Experience', descAr:'نصمّم تجارب متكاملة ترفع رضا المستفيدين وتعزّز كفاءة القنوات والخدمات الرقمية من البداية إلى النهاية.', descEn:'We design end-to-end experiences that improve beneficiary satisfaction and the efficiency of digital channels and services.', pointsAr:['أبحاث المستفيد ورحلاته','تصميم وتطوير الخدمات','قياس الرضا والتحسين المستمر'], pointsEn:['Beneficiary research and journeys','Service design and improvement','Satisfaction and continuous improvement'] },
  { n:'08', glyph:'□', ar:'إدارة الجودة الشاملة', en:'Total Quality Management', descAr:'نُعيد هندسة العمليات ونطوّر أنظمة الجودة لرفع الكفاءة وتسريع الإنجاز وبناء ثقافة التحسين المستمر.', descEn:'We redesign processes and develop quality systems to improve efficiency, accelerate delivery, and embed continuous improvement.', pointsAr:['نمذجة وإعادة هندسة العمليات','أنظمة وسياسات إدارة الجودة','مؤشرات الأداء والتحسين'], pointsEn:['Process modeling and re-engineering','Quality management systems and policies','Performance and improvement indicators'] },
];
const projects = [
  { no:'01', clientAr:'جامعة القصيم', clientEn:'Qassim University', typeAr:'التحول الرقمي', typeEn:'Digital Transformation', titleAr:'خارطة طريق التحول الرقمي المؤسسي', titleEn:'Institutional Digital Transformation Roadmap', descAr:'تشخيص النضج الرقمي وتحديد المبادرات ذات الأولوية وبناء خارطة تنفيذ مترابطة تدعم مستهدفات الجامعة.', descEn:'Assessing digital maturity, prioritizing initiatives, and building an integrated execution roadmap aligned with the university’s goals.', tagsAr:['قياس النضج','خارطة الطريق','حوكمة المبادرات'], tagsEn:['Maturity','Roadmap','Governance'], tone:'violet' },
  { no:'02', clientAr:'جامعة القصيم', clientEn:'Qassim University', typeAr:'البنية المؤسسية', typeEn:'Enterprise Architecture', titleAr:'تأسيس وتفعيل البنية المؤسسية', titleEn:'Enterprise Architecture Establishment', descAr:'تصميم نموذج التشغيل وبناء المعماريات الحالية والمستهدفة وربطها بمحفظة المبادرات والتقنيات.', descEn:'Designing the operating model, developing baseline and target architectures, and linking them to the initiative and technology portfolio.', tagsAr:['نموذج التشغيل','المعماريات','المحفظة التقنية'], tagsEn:['Operating Model','Architectures','Technology Portfolio'], tone:'navy' },
  { no:'03', clientAr:'الهيئة السعودية للملكية الفكرية', clientEn:'Saudi Authority for Intellectual Property', typeAr:'التحول الرقمي', typeEn:'Digital Transformation', titleAr:'برنامج تمكين التحول الرقمي', titleEn:'Digital Transformation Enablement Program', descAr:'مواءمة مستهدفات التحول مع الأولويات المؤسسية، وتطوير نموذج متابعة يقيس التقدم والأثر بوضوح.', descEn:'Aligning transformation goals with institutional priorities and developing a monitoring model that clearly measures progress and impact.', tagsAr:['الاستراتيجية','القياس','إدارة التغيير'], tagsEn:['Strategy','Measurement','Change'], tone:'blue' },
  { no:'04', clientAr:'الهيئة السعودية للملكية الفكرية', clientEn:'Saudi Authority for Intellectual Property', typeAr:'البنية المؤسسية', typeEn:'Enterprise Architecture', titleAr:'مواءمة الأعمال والتقنية', titleEn:'Business–Technology Alignment', descAr:'تطوير مرجعيات البنية المؤسسية وآليات الحوكمة لدعم القرارات الاستثمارية وتحسين التكامل بين الأعمال والتقنية.', descEn:'Developing enterprise architecture references and governance mechanisms to guide investment decisions and improve business–technology integration.', tagsAr:['هندسة الأعمال','حوكمة التقنية','المرجعيات'], tagsEn:['Business Architecture','IT Governance','Reference Models'], tone:'sand' },
];
const copy = {
  ar: { nav:['من نحن','الخدمات','المنهجية','المشاريع','تواصل معنا'], eyebrow:'شريكك في التحول المؤسسي', title:'نحوّل الطموح الرقمي إلى أثرٍ مؤسسي.', intro:'نعمل من داخل المنظومة لربط الاستراتيجية بالتنفيذ، وبناء قدرات رقمية مستدامة وقابلة للقياس.', primary:'استكشف خدماتنا', secondary:'ابدأ رحلتك الرقمية', marker:'خبرات وطنية · أثر قابل للقياس', heroStat:'مجالات خبرة متكاملة', aboutLabel:'من نحن', aboutTitle:'نبني التحول من داخل المنظومة.', aboutText:'ركيزة التحول شركة استشارية سعودية متخصصة في تمكين الجهات من تحويل المبادرات الرقمية المتفرقة إلى أثر مؤسسي مستدام. يجمع فريقنا بين الرؤية الاستراتيجية والخبرة التنفيذية لنصنع حلولاً تتبنّاها فرق العمل وتستمر بعد انتهاء المشروع.', values:[['فريق وطني','استشاريون ومحللو أعمال بخبرة في القطاع الحكومي'],['منهجية عملية','مخرجات قابلة للتطبيق والقياس منذ اليوم الأول'],['شراكة حقيقية','نقل معرفة وبناء قدرات داخلية مستدامة']], servicesLabel:'خدماتنا', servicesTitle:'خبرة متكاملة. أثر واحد.', servicesIntro:'ثمانية مجالات مترابطة تأخذ منظمتك من التشخيص والتخطيط إلى التنفيذ والتحسين المستمر.', details:'تفاصيل الخدمة', outputs:'ما الذي نقدّمه', methodLabel:'طريقتنا', methodTitle:'منهجية واضحة من أربع خطوات', steps:[['01','نفهم','نفهم السياق والطموح والتحديات من أصحاب المصلحة.'],['02','نُشخّص','نقيس الوضع الراهن ونحدّد الفجوات والأولويات.'],['03','نصمّم','نبني الحل وخارطة الطريق ومؤشرات النجاح.'],['04','نُمكّن','ننفّذ مع فرقكم وننقل المعرفة ونقيس الأثر.']], projectsLabel:'مشاريع حديثة', projectsTitle:'شراكات تصنع أثراً مستداماً', projectsIntro:'نماذج من أعمالنا في التحول الرقمي والبنية المؤسسية مع جهات وطنية رائدة.', contactLabel:'لنبدأ الحوار', contactTitle:'جاهزون لتحويل التحدّي القادم إلى فرصة.', contactText:'شاركنا احتياجك، وسيتواصل معك فريقنا لمناقشة المسار الأنسب.', fields:['الاسم الكامل','البريد الإلكتروني','الجهة / المنظمة','كيف يمكننا مساعدتك؟'], send:'إرسال الطلب عبر واتساب', direct:'أو تواصل معنا مباشرة', rights:'© 2026 شركة ركيزة التحول — المملكة العربية السعودية' },
  en: { nav:['About','Services','Approach','Projects','Contact'], eyebrow:'Your institutional transformation partner', title:'Turning digital ambition into institutional impact.', intro:'We work from within your ecosystem to connect strategy with execution and build sustainable, measurable digital capabilities.', primary:'Explore our services', secondary:'Start your digital journey', marker:'National expertise · Measurable impact', heroStat:'Integrated areas of expertise', aboutLabel:'About us', aboutTitle:'We build transformation from within.', aboutText:'Transformation Pillar Company is a Saudi consultancy that helps organizations turn fragmented digital initiatives into lasting institutional impact. Our team combines strategic vision with hands-on delivery to create solutions that teams adopt and sustain beyond the engagement.', values:[['National team','Consultants and business analysts with government-sector expertise'],['Practical approach','Actionable, measurable outputs from day one'],['True partnership','Knowledge transfer and sustainable internal capability building']], servicesLabel:'Our services', servicesTitle:'Integrated expertise. One impact.', servicesIntro:'Eight connected domains that take your organization from assessment and planning to execution and continuous improvement.', details:'Service details', outputs:'What we deliver', methodLabel:'Our approach', methodTitle:'A clear four-step methodology', steps:[['01','Understand','We uncover the context, ambition, and stakeholder challenges.'],['02','Assess','We measure the current state and identify gaps and priorities.'],['03','Design','We shape the solution, roadmap, and success measures.'],['04','Enable','We execute with your teams, transfer knowledge, and measure impact.']], projectsLabel:'Recent projects', projectsTitle:'Partnerships that create lasting impact', projectsIntro:'Selected digital transformation and enterprise architecture engagements with leading national entities.', contactLabel:'Start a conversation', contactTitle:'Ready to turn your next challenge into an opportunity.', contactText:'Tell us what you need and our team will reach out to discuss the best path forward.', fields:['Full name','Email address','Organization','How can we help?'], send:'Send request via WhatsApp', direct:'Or reach us directly', rights:'© 2026 Transformation Pillar Company — Saudi Arabia' },
};

export default function Home() {
  const [lang, setLang] = useState<Lang>('ar');
  const ar = lang === 'ar'; const t = copy[lang];
  const anchors = ['#about','#services','#approach','#projects','#contact'];
  function submitContact(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const data = new FormData(event.currentTarget);
    const message = ar ? `مرحباً، أنا ${data.get('name')} من ${data.get('organization')}. ${data.get('message')} — ${data.get('email')}` : `Hello, I’m ${data.get('name')} from ${data.get('organization')}. ${data.get('message')} — ${data.get('email')}`;
    window.open(`https://wa.me/966505527636?text=${encodeURIComponent(message)}`, '_blank', 'noopener,noreferrer');
  }
  return (
    <main dir={ar ? 'rtl' : 'ltr'} className="site-shell">
      <header className="topbar"><a href="#top" className="brand" aria-label="TPCO home"><span className="brand-mark"><img src="/tpco-mark.svg" alt="" /></span><span><b>ركيزة التحول</b><small>Transformation Pillar</small></span></a><nav aria-label="Primary navigation">{t.nav.map((item,index)=><a key={item} href={anchors[index]}>{item}</a>)}</nav><button className="lang-switch" onClick={()=>setLang(ar?'en':'ar')} aria-label="Switch language">{ar?'EN':'عربي'}</button></header>
      <section className="hero" id="top"><div className="hero-copy"><p className="eyebrow"><span />{t.eyebrow}</p><h1>{t.title}</h1><p className="hero-intro">{t.intro}</p><div className="hero-actions"><a className="button primary" href="#services">{t.primary}<span>↗</span></a><a className="button ghost" href="https://wa.me/966505527636" target="_blank" rel="noreferrer">{t.secondary}</a></div><p className="marker">{t.marker}</p></div><div className="hero-visual" aria-label="Saudi transformation consultant"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><img src="/hero-natural.png" alt={ar?'مستشار سعودي في التحول الرقمي':'Saudi digital transformation consultant'} /><div className="impact-card"><small>{t.heroStat}</small></div></div></section>
      <section className="about section-pad" id="about"><div className="about-head"><div><p className="eyebrow dark"><span />{t.aboutLabel}</p><h2>{t.aboutTitle}</h2></div><p className="lead-copy">{t.aboutText}</p></div><div className="value-grid">{t.values.map(value=><article key={value[0]}><h3>{value[0]}</h3><p>{value[1]}</p></article>)}</div></section>
      <section className="services section-pad" id="services"><div className="section-heading light"><div><p className="eyebrow"><span />{t.servicesLabel}</p><h2>{t.servicesTitle}</h2></div><p>{t.servicesIntro}</p></div><div className="services-grid-full">{services.map(service=><details className="service-detail" key={service.n}><summary><div className="service-top"><b className="glyph">{service.glyph}</b></div><h3>{ar?service.ar:service.en}</h3><p>{ar?service.descAr:service.descEn}</p><span className="detail-link">{t.details}<b>＋</b></span></summary><div className="detail-body"><b>{t.outputs}</b><ul>{(ar?service.pointsAr:service.pointsEn).map(point=><li key={point}>{point}</li>)}</ul></div></details>)}</div></section>
      <section className="approach section-pad" id="approach"><p className="eyebrow dark"><span />{t.methodLabel}</p><h2>{t.methodTitle}</h2><div className="steps">{t.steps.map(step=><article key={step[0]}><div className="step-dot" /><h3>{step[1]}</h3><p>{step[2]}</p></article>)}</div></section>
      <section className="projects section-pad" id="projects"><div className="section-heading project-heading"><div><p className="eyebrow dark"><span />{t.projectsLabel}</p><h2>{t.projectsTitle}</h2></div><p>{t.projectsIntro}</p></div><div className="project-grid">{projects.map(project=><article className={`project-card ${project.tone}`} key={project.no}><div className="project-visual"><div className="project-rings"><i/><i/><i/></div><span className="project-type">{ar?project.typeAr:project.typeEn}</span></div><div className="project-copy"><small>{ar?project.clientAr:project.clientEn}</small><h3>{ar?project.titleAr:project.titleEn}</h3><p>{ar?project.descAr:project.descEn}</p><div className="tags">{(ar?project.tagsAr:project.tagsEn).map(tag=><span key={tag}>{tag}</span>)}</div></div></article>)}</div></section>
      <section className="contact section-pad" id="contact"><div className="contact-copy"><p className="eyebrow"><span />{t.contactLabel}</p><h2>{t.contactTitle}</h2><p>{t.contactText}</p><div className="contact-direct"><small>{t.direct}</small><a href="https://wa.me/966505527636" target="_blank" rel="noreferrer">+966 50 552 7636 ↗</a></div></div><form onSubmit={submitContact}><label>{t.fields[0]}<input required name="name" autoComplete="name" /></label><label>{t.fields[1]}<input required type="email" name="email" autoComplete="email" /></label><label>{t.fields[2]}<input required name="organization" autoComplete="organization" /></label><label className="full">{t.fields[3]}<textarea required name="message" rows={3} /></label><button className="button primary full" type="submit">{t.send}<span>↗</span></button></form></section>
      <footer><a href="#top" className="brand"><span className="brand-mark"><img src="/tpco-mark.svg" alt="" /></span><span><b>ركيزة التحول</b><small>Transformation Pillar</small></span></a><p>{t.rights}</p><a href="#top" className="back-top">↑</a></footer>
    </main>
  );
}
